const puppeteer = require('puppeteer')

let URL_INSTALL = 'http://localhost:8001/install-dev/'
let URL_BO = 'http://localhost:8001/admin722wzfume/'
let URL_BO2 = 'http://localhost:8001/admin-dev/'
let EMAIL = 'demo@prestashop.com'
let PASSWORD2 = 'prestashop'
let PASSWORD = 'prestashop_demo'


const getListOfModules = async () => {
  const browser = await puppeteer.launch({ headless: false })
  const page = await browser.newPage()
  await page.tracing.start({
    path: 'trace.json',
    categories: ['devtools.timeline']
  })
  await page.goto(URL_BO)

  await page.setViewport({ width: 1500, height: 2500 })
  await page.waitFor('body')
  await page.type('#email', EMAIL)
  await page.type('#passwd', PASSWORD)
  await page.click('#submit_login')
  await page.waitFor('header')
  console.log("Dashboard")
  await page.click('#tab-AdminDashboard')
  await page.screenshot({ path: "screenshot1.png" })
  console.log("Orders")
  await page.waitFor('#subtab-AdminParentOrders')
  await page.click('#subtab-AdminParentOrders')
  await page.screenshot({ path: "screenshot2.png" })

  await page.waitFor('#subtab-AdminOrders')
  await page.click('#subtab-AdminOrders')
  await page.screenshot({ path: "screenshot3.png" })

  await page.waitFor('#subtab-AdminInvoices')
  await page.click('#subtab-AdminInvoices')
  await page.screenshot({ path: "screenshot4.png" })

  await page.waitFor('#subtab-AdminSlip')
  await page.click('#subtab-AdminSlip')
  await page.screenshot({ path: "screenshot5.png" })

  await page.waitFor('#subtab-AdminDeliverySlip')
  await page.click('#subtab-AdminDeliverySlip')
  await page.waitFor('#subtab-AdminCarts')
  await page.click('#subtab-AdminCarts')
  await page.waitFor('#subtab-AdminCatalog')
  console.log("Catalog")
  await page.click('#subtab-AdminCatalog')
  await page.waitFor('#subtab-AdminProducts')
  await page.click('#subtab-AdminProducts')
  await page.waitFor('#subtab-AdminCategories')
  await page.click('#subtab-AdminCategories')
  await page.waitFor('#subtab-AdminTracking')
  await page.click('#subtab-AdminTracking')
  await page.waitFor('#subtab-AdminParentAttributesGroups')
  await page.click('#subtab-AdminParentAttributesGroups')
  await page.waitFor('#subtab-AdminParentManufacturers')
  await page.click('#subtab-AdminParentManufacturers')
  await page.waitFor('#subtab-AdminAttachments')
  await page.click('#subtab-AdminAttachments')
  await page.waitFor('#subtab-AdminParentCartRules')
  await page.click('#subtab-AdminParentCartRules')
  await page.waitFor('#subtab-AdminStockManagement')
  await page.click('#subtab-AdminStockManagement')
  console.log("Customers")
  await page.waitFor('#subtab-AdminParentCustomer')
  await page.click('#subtab-AdminParentCustomer')
  await page.waitFor('#subtab-AdminCustomers')
  await page.click('#subtab-AdminCustomers')
  await page.waitFor('#subtab-AdminAddresses')
  await page.click('#subtab-AdminAddresses')
  await page.waitFor(4000)
  console.log("Customer Service")
  await page.waitFor('#subtab-AdminParentCustomerThreads')
  await page.click('#subtab-AdminParentCustomerThreads')
  await page.waitFor(2000)
  await page.waitFor('#subtab-AdminCustomerThreads')
  await page.click('#subtab-AdminCustomerThreads')
  await page.waitFor(2000)
  await page.waitFor('#subtab-AdminOrderMessage')
  await page.click('#subtab-AdminOrderMessage')
  await page.waitFor(4000)
  await page.waitFor('#subtab-AdminReturn')
  await page.click('#subtab-AdminReturn')
  await page.waitFor(4000)
  console.log("Stats")
  await page.waitFor('#subtab-AdminStats')
  await page.waitFor(2000)
  await page.click('#subtab-AdminStats')
  console.log("Modules")
  await page.waitFor('#subtab-AdminParentModulesSf')
  await page.click('#subtab-AdminParentModulesSf')
  await page.waitFor('#subtab-AdminModulesSf')
  await page.click('#subtab-AdminModulesSf')
  await page.waitFor('#subtab-AdminAddonsCatalog')
  await page.click('#subtab-AdminAddonsCatalog')
  console.log("Design")
  await page.waitFor('#subtab-AdminParentThemes')
  await page.click('#subtab-AdminParentThemes')
  await page.waitFor('#subtab-AdminThemes')
  await page.click('#subtab-AdminThemes')
  await page.waitFor('#subtab-AdminThemesCatalog')
  await page.click('#subtab-AdminThemesCatalog')
  await page.waitFor('#subtab-AdminCmsContent')
  await page.click('#subtab-AdminCmsContent')
  await page.waitFor('#subtab-AdminModulesPositions')
  await page.click('#subtab-AdminModulesPositions')
  await page.waitFor('#subtab-AdminImages')
  await page.click('#subtab-AdminImages')
  await page.waitFor('#subtab-AdminLinkWidget')
  await page.click('#subtab-AdminLinkWidget')
  console.log("Shipping")
  await page.waitFor('#subtab-AdminParentShipping')
  await page.click('#subtab-AdminParentShipping')
  await page.waitFor('#subtab-AdminCarriers')
  await page.click('#subtab-AdminCarriers')
  await page.waitFor('#subtab-AdminShipping')
  await page.click('#subtab-AdminShipping')
  console.log("Payment")
  await page.waitFor('#subtab-AdminParentPayment')
  await page.click('#subtab-AdminParentPayment')
  await page.waitFor('#subtab-AdminPayment')
  await page.click('#subtab-AdminPayment')
  await page.waitFor('#subtab-AdminPaymentPreferences')
  await page.click('#subtab-AdminPaymentPreferences')
  console.log("International")
  await page.waitFor('#subtab-AdminInternational')
  await page.click('#subtab-AdminInternational')
  await page.waitFor('#subtab-AdminParentLocalization')
  await page.click('#subtab-AdminParentLocalization')
  await page.waitFor('#subtab-AdminParentCountries')
  await page.click('#subtab-AdminParentCountries')
  await page.waitFor('#subtab-AdminParentTaxes')
  await page.click('#subtab-AdminParentTaxes')
  await page.waitFor('#subtab-AdminTranslations')
  await page.click('#subtab-AdminTranslations')
  console.log("Shop Parameters")
  await page.waitFor('#subtab-ShopParameters')
  await page.click('#subtab-ShopParameters')
  await page.waitFor('#subtab-AdminParentPreferences')
  await page.click('#subtab-AdminParentPreferences')
  await page.waitFor('#subtab-AdminParentOrderPreferences')
  await page.click('#subtab-AdminParentOrderPreferences')
  await page.waitFor('#subtab-AdminPPreferences')
  await page.click('#subtab-AdminPPreferences')
  await page.waitFor('#subtab-AdminParentCustomerPreferences')
  await page.click('#subtab-AdminParentCustomerPreferences')
  await page.waitFor('#subtab-AdminParentStores')
  await page.click('#subtab-AdminParentStores')
  await page.waitFor('#subtab-AdminParentMeta')
  await page.click('#subtab-AdminParentMeta')
  await page.waitFor('#subtab-AdminParentSearchConf')
  await page.click('#subtab-AdminParentSearchConf')
  await page.waitFor('#subtab-AdminGamification')
  await page.click('#subtab-AdminGamification')
  console.log("Advanced Parameters")
  await page.waitFor('#subtab-AdminAdvancedParameters')
  await page.click('#subtab-AdminAdvancedParameters')
  await page.waitFor('#subtab-AdminInformation')
  await page.click('#subtab-AdminInformation')
  await page.waitFor('#subtab-AdminPerformance')
  await page.click('#subtab-AdminPerformance')
  await page.waitFor('#subtab-AdminAdminPreferences')
  await page.click('#subtab-AdminAdminPreferences')
  await page.waitFor('#subtab-AdminEmails')
  await page.click('#subtab-AdminEmails')
  await page.waitFor('#subtab-AdminImport')
  await page.click('#subtab-AdminImport')
  await page.waitFor('#subtab-AdminParentEmployees')
  await page.click('#subtab-AdminParentEmployees')
  await page.waitFor('#subtab-AdminParentRequestSql')
  await page.click('#subtab-AdminParentRequestSql')
  await page.waitFor('#subtab-AdminLogs')
  await page.click('#subtab-AdminLogs')
  await page.waitFor('#subtab-AdminWebservice')
  await page.click('#subtab-AdminWebservice')

  await page.waitFor(1500)

  await page.tracing.stop();
  await browser.close()
  }

getListOfModules()
